### ISSUE TITLE
Filter branch

### ISSUE THREAD

**Issue by joshmoore** [ome/omero-matlab#1]
https://github.com/openmicroscopy/openmicroscopy/tree/develop/components/tools/OmeroM needs extracting from the main build.

**Comment by sbesson** [comment]
If we are extracting this component, https://github.com/openmicroscopy/openmicroscopy/tree/develop/examples/Training/matlab might also be included in the filter branch operation or moved to e.g. `omero-examples` to prevent circular dependencies

**Comment by joshmoore** [comment]
Running this now:

```
git filter-branch --index-filter 'git rm --cached -qr --ignore-unmatch -- . && git reset -q $GIT_COMMIT -- components/tools/OmeroM examples/Training/matlab' --prune-empty -- --all

```

**Comment by joshmoore** [comment]
Please review https://github.com/ome/omero-matlab/releases/tag/v5.4.8-filtered and re-open this issue if necessary. I'll prepare the renaming of the files PR now. (We can decide whether we merge that first or @kouichi-c-nakamura's PR first there.)
