### ISSUE TITLE
Upgrade check

### ISSUE THREAD

**Issue by jburel** [ome/omero-matlab#25]
currently omero.matlab does not registered
The approach taken in insight is to access the value of ``omero.upgrades.url`` via the config service i.e. ``session.getConfigService().getConfigValue("omero.upgrades.url");``
This approach makes sense from a client perspective

Such approach will not always work in the toolbox since we have methods allowing to create a client only and session afterwards e.g.
```
client = loadOmero(host, port);
session = client.createSession(user, password);
```
i.e. the toolbox will not register unless actively added to the code

cc @sbesson @mtbc

**Comment by joshmoore** [comment]
What was the outcome here?

**Comment by jburel** [comment]
discussed with @sbesson, we need to work on it from all aspects (including BF) and rework the registration logic post decoupling
Matlab never registered
